improved trade button
Vilsol/timeless-jewels pull request #21
Opened 2023-12-20 15:10 UTC by shafouz

Rewrote the function that makes the search queries, now:
![screenshot-20231220-150009Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/f1fecf09-af65-446b-9ac8-7337c20da260)

only searches for the conqueror that you chose:

![screenshot-20231220-145544Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/78f8d083-cc6e-441e-bc99-5992f78f7b5a)

but using:

![screenshot-20231220-150523Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/b0fe37f4-8977-4c0f-ac42-b4c0de27d66c)

has the same behaviour as before:
![screenshot-20231220-145601Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/cd3fb8ef-5e97-43cf-903f-ce779c7750cf)

and more importantly, there should not be a problem of the query size getting too big, since we trim if it goes beyond a limit

```javascript
if (final_query.length > max_query_length) {
    final_query = final_query.slice(0, max_query_length)
}
```

2023-12-20 16:10 UTC, Vilsol requested changes

2023-12-20 16:10 UTC, Vilsol commented on frontend/src/lib/skill_tree.ts
> +  return gen_final_query(final_query)
Is there a reason why this is a function, if it only gets called once? Seems to just add confusion and misdirection.

2023-12-20 16:10 UTC, Vilsol commented on frontend/src/routes/tree/+page.svelte
> +                  on:click={() => openTrade(searchJewel, searchConqueror, searchResults.raw, true)}
I would still like to retain the logic, that if it can, it should generate for all conquerors.

2023-12-20 16:41 UTC, shafouz commented
Changed as requested, the only difference is that now it shows a little less results. I set the query limit by trial and error but it should rarely fail if it does

2023-12-20 16:45 UTC, Vilsol commented
It seems like you just removed the retry code and added a filter in a different way?

2023-12-20 16:53 UTC, shafouz commented
Yes, instead of checking if the url size is too big and handling it, now we trim it down to a size that should work always

2023-12-20 17:13 UTC, Vilsol commented
Yes, but previously, if all conquerors would fit in the query, it would generate one for all conquerors. If not, it falls back to a single one and trims it.

When they fit:
![image](https://github.com/Vilsol/timeless-jewels/assets/1759390/dbd4a32b-2ab0-4942-a994-1839ff0db49b)

When they don't:
![image](https://github.com/Vilsol/timeless-jewels/assets/1759390/e8e03785-9973-44ac-83e2-44535a4e7f40)

In your edit, it now generates one giant list containing all of them, but it cuts off.

![image](https://github.com/Vilsol/timeless-jewels/assets/1759390/885c8776-02be-417c-8019-b58b0415237f)

The tool should always prioritize showing the most available seeds for the conqueror selected.

2023-12-20 17:18 UTC, shafouz commented
Oh, i see. I'll change to that.

2023-12-20 18:53 UTC, shafouz commented
All seeds:
![screenshot-20231220-183821Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/98ca14bd-4001-417c-90b4-ad372e21a7f1)

Single seed:
![screenshot-20231220-183807Z-selected](https://github.com/Vilsol/timeless-jewels/assets/38974831/3f346bf9-a692-4352-bad6-57b5051af171)

The maximum amount of seeds in a query is 60 per conqueror before it stops working. If there is more than that should it fall back to the single conqueror case?

2023-12-20 21:06 UTC, Vilsol commented
Please make the linter happy and also rename the PR to follow conventional commit guidelines.

2023-12-21 09:28 UTC, Vilsol approved these changes

2023-12-21 09:28 UTC, merged